//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.encargo = new HashSet<encargo>();
        }
    
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
    
        public virtual ICollection<encargo> encargo { get; set; }
    }
}
