//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class encargo
    {
        public encargo()
        {
            this.venta = new HashSet<venta>();
        }
    
        public int id_encargo { get; set; }
        public System.DateTime fecha_encargo { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public string detalle_encargo { get; set; }
        public int id_cliente { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
