//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public inventario()
        {
            this.receta = new HashSet<receta>();
        }
    
        public int id_Inventario { get; set; }
        public string producto { get; set; }
        public decimal gasto_producto { get; set; }
        public int id_categoria { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual ICollection<receta> receta { get; set; }
    }
}
