//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasteles
    {
        public pasteles()
        {
            this.detalle = new HashSet<detalle>();
        }
    
        public int id_pastel { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public int id_receta { get; set; }
    
        public virtual ICollection<detalle> detalle { get; set; }
        public virtual receta receta { get; set; }
    }
}
