//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class receta
    {
        public receta()
        {
            this.pasteles = new HashSet<pasteles>();
        }
    
        public int id_receta { get; set; }
        public int id_Inventario { get; set; }
    
        public virtual inventario inventario { get; set; }
        public virtual ICollection<pasteles> pasteles { get; set; }
    }
}
