//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public pedido()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int id_pedido { get; set; }
        public System.DateTime fecha { get; set; }
        public string detalle { get; set; }
        public decimal precio { get; set; }
        public int cantidad { get; set; }
        public int id_proveedor { get; set; }
    
        public virtual proveedor proveedor { get; set; }
        public virtual ICollection<producto> producto { get; set; }
    }
}
