//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles
    {
        public roles()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_rol { get; set; }
        public string rol { get; set; }
    
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
