//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.venta = new HashSet<venta>();
        }
    
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string clave { get; set; }
        public int id_rol { get; set; }
    
        public virtual roles roles { get; set; }
        public virtual ICollection<venta> venta { get; set; }
    }
}
