//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary2
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.producto = new HashSet<producto>();
        }
    
        public int id_venta { get; set; }
        public System.DateTime fecha { get; set; }
        public int cantidad { get; set; }
        public decimal total_venta { get; set; }
        public int dui { get; set; }
        public int id_usuario { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<producto> producto { get; set; }
    }
}
